run:
  concurrency: 4
  deadline: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
  skip-dirs:
    - vendor
  skip-files:
    - .*easyjson.*
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
    ignore: 'fmt:.*,io/ioutil:^Read.*'
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/clobucks
  gocyclo:
    min-complexity: 20
  goconst:
    min-len: 3
    min-occurrences: 3
  depguard:
    list-type: blacklist
    include-go-root: false
  misspell:
    locale: US
  lll:
    line-length: 150
    tab-width: 4
  unused:
    check-exported: false
  unparam:
    check-exported: true
  nakedret:
    max-func-lines: 1
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  gocritic:
    disabled-checks: null
    enabled-tags:
      - performance
      - diagnostic
    settings:
      captLocal:
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 32
linters:
  enable-all: true
  fast: false
  disable:
    - wsl
    - gomnd
    - funlen
    - lll
    - dupl
    - exhaustivestruct
    - godox
    - unparam
    - maligned
    - gochecknoglobals
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  new: false

